### ISSUE TITLE
https://webpro.nl/ returns 404

### ISSUE THREAD

**Issue by uwemaurer** [webpro/webpro.nl#4]
I was reading your blog posts and noticed that the main page ( https://webpro.nl/ ) returns a 404

**Comment by webpro** [comment]
Thanks, Uwe! Yet it looks alright to me, also see https://downforeveryoneorjustme.com/webpro.nl

**Comment by uwemaurer** [comment]
![image](https://github.com/user-attachments/assets/40b767f1-2cb2-4f69-99af-3934ddf6a3c0)

**Comment by uwemaurer** [comment]
I just tried from a different IP address (in the US) and there I can load it.

However I see in the HTML

```
<meta property="article:modified_time" content="2024-11-09T00:00:00.000Z">

<meta name="generator" content="Astro v4.16.10">
```

so this is probaby an old cached version

**Comment by webpro** [comment]
lol wonderful service

<img width="558" alt="Screenshot 2024-12-09 at 1 11 02 PM" src="https://github.com/user-attachments/assets/8f2fd42b-5d8e-48b8-ba3c-48f97df56b71">

The usual suspects with `traceroute`, `dig ns` and `ping` seem OK as well.

This is all green: https://dnschecker.org/#A/webpro.nl

Still wonder why https://downforeveryoneorjustme.com/webpro.nl gives different results, and why you're still seeing that cached version, though.

**Comment by uwemaurer** [comment]
yes ping and DNS just go to cloudflare servers and is working.

I see these response headers

```
< date: Mon, 09 Dec 2024 12:23:37 GMT
< content-type: text/html; charset=utf-8
< cf-cache-status: DYNAMIC
< access-control-allow-origin: *
< age: 461721
< cache-control: public, s-maxage=604800
```

this allows caching for up to 7 days, and `age` is 5 days. 
I saw in your commit history that you updated Astro 5 days ago, so probably the old version can still be served 2 more days.

I recommend to log into cloudflare and go to Caching and do "Purge Everything"

this still doesn't explain the 404 I get from my home IP though

**Comment by webpro** [comment]
Thanks, I've just purged everything.

Odd that Browser Cache TTL setting in CF is set to 4 hours. Also waited a bit but shouldn't `age` get "reset" after cache purge?

```
❯ curl -I https://webpro.nl
HTTP/2 200 
date: Mon, 09 Dec 2024 12:45:12 GMT
content-type: text/html; charset=utf-8
cf-cache-status: DYNAMIC
access-control-allow-origin: *
age: 430735
cache-control: public, s-maxage=604800
```

Not seeing other cache config that's off. Thanks a lot for your help! Please don't feel obliged to dig further.

**Comment by webpro** [comment]
dang, turns out that some build script I was running in cloudflare messed up the root `index.html` 🤦‍♂️

well, problem solved. thanks again @uwemaurer!
